# Generated by Django 4.1.3 on 2022-11-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LILImagesModel',
            fields=[
                ('imageid', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('tags', models.TextField()),
                ('url', models.CharField(max_length=512)),
                ('permlink', models.CharField(max_length=512)),
                ('author', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'images',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LILRatingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'lmacg_ratings',
                'managed': False,
            },
        ),
    ]
