# Generated by Django 4.1.3 on 2022-12-16 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lilGallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lilratingsmodel',
            options={'managed': False, 'permissions': [('rate_image', 'Allowed to rate an image.')]},
        ),
    ]
