# Generated by Django 4.1.3 on 2022-12-27 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lilGallery', '0003_liltagsmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lilimagesmodel',
            options={'managed': False, 'verbose_name': 'LIL Image'},
        ),
    ]
