# Generated by Django 4.1.3 on 2023-09-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LMACAPIAccessModel',
            fields=[
                ('_apiKey', models.CharField(db_column='apiKey', max_length=512, primary_key=True, serialize=False, unique=True)),
                ('_contingentLeft', models.IntegerField(db_column='contingentLeft', default=0)),
            ],
            options={
                'verbose_name': 'LMAC API Access',
                'db_table': 'LMACAPIAccess',
                'managed': False,
            },
        ),
    ]