# Generated by Django 4.1.3 on 2022-12-27 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmacPoll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lmacpollposttemplatemodel',
            options={'managed': True, 'permissions': [('manage poll post templates', 'Allows to manage poll post templates.')], 'verbose_name': 'Poll Post Template'},
        ),
    ]
