# Generated by Django 4.1.3 on 2022-12-27 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmacPoll', '0002_alter_lmacpollposttemplatemodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmacpollposttemplatemodel',
            name='category',
            field=models.CharField(default='hive-1746952', max_length=256),
        ),
    ]
