# Generated by Django 4.1.3 on 2023-01-27 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LMACWinnersModel',
            fields=[
                ('contestId', models.IntegerField(max_length=48, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('postUrl', models.CharField(max_length=512)),
                ('templateImageUrl', models.CharField(max_length=512)),
                ('winners', models.TextField()),
                ('isVisible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'LMAC Contests',
                'db_table': 'lmac_contests',
                'managed': False,
            },
        ),
    ]
