# Generated by Django 4.1.3 on 2023-09-16 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmacWinners', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lmacwinnersmodel',
            options={'managed': True, 'verbose_name': 'LMAC Contests'},
        ),
    ]
