# Generated by Django 4.1.3 on 2022-11-26 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticContentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.CharField(max_length=48)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_home_page', models.BooleanField(default=False)),
                ('created_date', models.DateField()),
                ('title', models.CharField(max_length=256)),
                ('body', models.TextField()),
            ],
        ),
    ]
