# Generated by Django 4.1.3 on 2022-12-27 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staticContentApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staticcontentmodel',
            options={'verbose_name': 'Static content'},
        ),
    ]
